import { NextResponse } from "next/server";
import { validateEvent } from "@polar-sh/sdk/webhooks";
import { createClient } from "@supabase/supabase-js";
import { Webhook } from "standardwebhooks";

export async function POST(request: Request) {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  const webhookSecret = process.env.POLAR_WEBHOOK_SECRET;

  if (!supabaseUrl || !serviceRoleKey || !webhookSecret) {
    return NextResponse.json(
      { error: "Polar webhook is not configured." },
      { status: 503 },
    );
  }

  const body = await request.text();
  const headers = Object.fromEntries(request.headers.entries());
  let event: ReturnType<typeof validateEvent>;

  try {
    try {
      // Supports Polar's legacy HMAC webhook secrets.
      event = validateEvent(body, headers, webhookSecret);
    } catch {
      // Supports Standard Webhooks secrets generated by newer Polar endpoints.
      const verifiedEvent = new Webhook(webhookSecret).verify(body, headers);
      if (
        typeof verifiedEvent !== "object" ||
        verifiedEvent === null ||
        !("timestamp" in verifiedEvent) ||
        !("data" in verifiedEvent) ||
        typeof verifiedEvent.timestamp !== "string" ||
        typeof verifiedEvent.data !== "object" ||
        verifiedEvent.data === null
      ) {
        throw new Error("Invalid Standard Webhooks event payload.");
      }

      const timestamp = new Date(verifiedEvent.timestamp);
      if (Number.isNaN(timestamp.getTime())) {
        throw new Error("Invalid Standard Webhooks event timestamp.");
      }

      const data = verifiedEvent.data as Record<string, unknown>;
      event = {
        ...verifiedEvent,
        timestamp,
        data: {
          ...data,
          checkoutId: data.checkoutId ?? data.checkout_id ?? null,
        },
      } as ReturnType<typeof validateEvent>;
    }
  } catch {
    return NextResponse.json(
      {
        error: "Invalid webhook signature.",
        hint: "Copy the secret from this exact Polar webhook endpoint into POLAR_WEBHOOK_SECRET and restart the server.",
      },
      { status: 401 },
    );
  }

  const paymentStatus =
    event.type === "order.paid"
      ? "paid"
      : event.type === "order.refunded"
        ? "refunded"
        : event.type === "checkout.expired"
          ? "expired"
          : null;

  if (!paymentStatus) {
    return NextResponse.json({ received: true });
  }

  let checkoutId: string | null = null;
  let polarOrderId: string | null = null;

  if (event.type === "checkout.expired") {
    checkoutId = event.data.id;
  } else if (event.type === "order.paid" || event.type === "order.refunded") {
    checkoutId = event.data.checkoutId;
    polarOrderId = event.data.id;
  }

  if (!checkoutId) {
    return NextResponse.json(
      { error: "Polar event is missing its checkout identifier." },
      { status: 400 },
    );
  }

  const admin = createClient(supabaseUrl, serviceRoleKey, {
    auth: { autoRefreshToken: false, persistSession: false },
  });
  const paymentQuery = admin
    .from("sponsorship_payments")
    .select(
      "id, user_id, polar_product_id, amount, currency, promotion_days",
    )
    .eq("polar_checkout_id", checkoutId);

  const { data: payment, error: paymentLookupError } =
    await paymentQuery.maybeSingle();

  if (paymentLookupError) {
    console.error("Could not look up sponsorship payment", paymentLookupError);
    return NextResponse.json(
      { error: "Could not process webhook." },
      { status: 500 },
    );
  }

  if (!payment) {
    return NextResponse.json({ received: true });
  }

  if (event.type === "order.paid" || event.type === "order.refunded") {
    const metadata = event.data.metadata;
    const matchingCheckout =
      event.data.productId === payment.polar_product_id &&
      event.data.currency.toLowerCase() === payment.currency.toLowerCase() &&
      metadata.user_id === payment.user_id &&
      metadata.promotion_days === payment.promotion_days &&
      metadata.sponsorship_amount === payment.amount;

    if (!matchingCheckout || (event.type === "order.paid" && !event.data.paid)) {
      console.error("Polar order did not match its sponsorship checkout", {
        checkoutId,
        orderId: event.data.id,
      });
      return NextResponse.json(
        { error: "Polar order did not match its sponsorship checkout." },
        { status: 400 },
      );
    }
  }

  const { error } = await admin.rpc("apply_polar_sponsorship_event", {
    p_payment_id: payment.id,
    p_status: paymentStatus,
    p_polar_order_id: polarOrderId,
    p_event_at: event.timestamp.toISOString(),
  });

  if (error) {
    console.error("Could not apply sponsorship event", error);
    return NextResponse.json(
      { error: "Could not process webhook." },
      { status: 500 },
    );
  }

  return NextResponse.json({ received: true });
}
