import { NextResponse } from "next/server";
import { validateEvent } from "@polar-sh/sdk/webhooks";
import { createClient } from "@supabase/supabase-js";
import { Webhook } from "standardwebhooks";

export async function POST(request: Request) {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  const webhookSecret = process.env.POLAR_WEBHOOK_SECRET;

  if (!supabaseUrl || !serviceRoleKey || !webhookSecret) {
    return NextResponse.json(
      { error: "Polar webhook is not configured." },
      { status: 503 },
    );
  }

  const body = await request.text();
  const headers = Object.fromEntries(request.headers.entries());
  let event: ReturnType<typeof validateEvent>;

  try {
    try {
      // Supports Polar's legacy HMAC webhook secrets.
      event = validateEvent(body, headers, webhookSecret);
    } catch {
      // Supports Standard Webhooks secrets generated by newer Polar endpoints.
      event = new Webhook(webhookSecret).verify(body, headers) as ReturnType<
        typeof validateEvent
      >;
    }
  } catch {
    return NextResponse.json(
      {
        error: "Invalid webhook signature.",
        hint: "Copy the secret from this exact Polar webhook endpoint into POLAR_WEBHOOK_SECRET and restart the server.",
      },
      { status: 401 },
    );
  }

  const paymentStatus =
    event.type === "order.paid"
      ? "paid"
      : event.type === "order.refunded"
        ? "refunded"
        : event.type === "checkout.expired"
          ? "expired"
          : null;

  if (!paymentStatus) {
    return NextResponse.json({ received: true });
  }

  let checkoutId: string | null = null;
  let polarOrderId: string | null = null;

  if (event.type === "checkout.expired") {
    checkoutId = event.data.id;
  } else if (event.type === "order.paid" || event.type === "order.refunded") {
    checkoutId = event.data.checkoutId;
    polarOrderId = event.data.id;
  }

  if (!checkoutId) {
    console.info("Polar order event using fallback payment correlation", {
      type: event.type,
      eventId: event.data.id,
    });
  }

  const admin = createClient(supabaseUrl, serviceRoleKey, {
    auth: { autoRefreshToken: false, persistSession: false },
  });
  let paymentQuery = admin
    .from("sponsorship_payments")
    .select("id, profile_id")
    .order("created_at", { ascending: false })
    .limit(1);

  if (checkoutId) {
    paymentQuery = paymentQuery.eq("polar_checkout_id", checkoutId);
  } else if (event.type === "order.paid" || event.type === "order.refunded") {
    const metadataUserId = event.data.metadata.user_id;
    const userId =
      typeof metadataUserId === "string"
        ? metadataUserId
        : event.data.customer.externalId;

    if (!userId) {
      return NextResponse.json({ received: true });
    }

    paymentQuery = paymentQuery
      .eq("user_id", userId)
      .eq("polar_product_id", event.data.productId ?? "")
      .in("status", ["pending", "paid"]);
  } else {
    return NextResponse.json({ received: true });
  }

  const { data: payment, error: paymentLookupError } =
    await paymentQuery.maybeSingle();

  if (paymentLookupError) {
    return NextResponse.json(
      { error: paymentLookupError.message },
      { status: 500 },
    );
  }

  if (!payment) {
    return NextResponse.json({ received: true });
  }

  const update = {
    status: paymentStatus,
    ...(polarOrderId ? { polar_order_id: polarOrderId } : {}),
    ...(event.type === "order.paid"
      ? { paid_at: event.timestamp.toISOString() }
      : {}),
  };

  const { error } = await admin
    .from("sponsorship_payments")
    .update(update)
    .eq("id", payment.id);

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  const { error: profileError } = await admin
    .from("profiles")
    .update({ is_sponsored: paymentStatus === "paid" })
    .eq("id", payment.profile_id);

  if (profileError) {
    return NextResponse.json({ error: profileError.message }, { status: 500 });
  }

  return NextResponse.json({ received: true });
}
