const roleNames = [
  // Design
  "Designer",
  "Graphic Designer",
  "UI Designer",
  "UX Designer",
  "UI/UX Designer",
  "Product Designer",
  "Visual Designer",
  "Brand Designer",
  "Interaction Designer",
  "Web Designer",
  "Editorial Designer",
  "Motion Designer",
  "Packaging Designer",
  "Fashion Designer",
  "Interior Designer",
  "Industrial Designer",
  "Experience Designer",
  "Service Designer",
  "Information Designer",
  "Type Designer",
  "Typography Designer",
  "Communication Designer",
  "Digital Designer",
  "Environmental Designer",
  "Exhibition Designer",
  "Furniture Designer",
  "Lighting Designer",
  "Signage Designer",
  "Wayfinding Designer",
  "Presentation Designer",
  "Publication Designer",
  "Print Designer",
  "Book Designer",
  "Layout Designer",
  "Design Director",
  "Design Lead",
  "Design Consultant",
  "Design Strategist",
  "Artisan",
  "Craftsperson",

  // Development & Technology
  "Developer",
  "Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Full-Stack Developer",
  "Web Developer",
  "Mobile Developer",
  "iOS Developer",
  "Android Developer",
  "React Developer",
  "React Native Developer",
  "Next.js Developer",
  "Vue Developer",
  "Angular Developer",
  "Svelte Developer",
  "Node.js Developer",
  "Python Developer",
  "Java Developer",
  "C# Developer",
  "C++ Developer",
  "PHP Developer",
  "Ruby Developer",
  "Go Developer",
  "Rust Developer",
  "Swift Developer",
  "Kotlin Developer",
  "TypeScript Developer",
  "JavaScript Developer",
  "WordPress Developer",
  "Shopify Developer",
  "Web3 Developer",
  "Blockchain Developer",
  "Smart Contract Developer",
  "Game Developer",
  "Game Programmer",
  "Creative Technologist",
  "Creative Developer",
  "Technical Artist",
  "DevOps Engineer",
  "Cloud Engineer",
  "Cloud Architect",
  "Data Engineer",
  "Data Scientist",
  "Machine Learning Engineer",
  "AI Engineer",
  "AI Developer",
  "AI Researcher",
  "Prompt Engineer",
  "Cybersecurity Specialist",
  "Cybersecurity Engineer",
  "Security Researcher",
  "Systems Engineer",
  "Network Engineer",
  "Network Administrator",
  "Database Administrator",
  "Database Engineer",
  "Solutions Architect",
  "Software Architect",
  "Systems Architect",
  "Cloud Architect",
  "QA Engineer",
  "QA Tester",
  "Test Engineer",
  "Automation Engineer",
  "Site Reliability Engineer",
  "Platform Engineer",
  "Embedded Systems Engineer",
  "Firmware Engineer",
  "Robotics Engineer",
  "Computer Vision Engineer",
  "NLP Engineer",
  "MLOps Engineer",
  "Data Analyst",
  "Business Intelligence Analyst",
  "Developer Advocate",
  "Technical Writer",
  "Technical Consultant",
  "IT Consultant",
  "IT Specialist",
  "IT Support Specialist",
  "Solutions Engineer",
  "Release Engineer",
  "Build Engineer",

  // Art & Illustration
  "Artist",
  "Illustrator",
  "Digital Artist",
  "Concept Artist",
  "Character Artist",
  "Storyboard Artist",
  "Comic Artist",
  "Manga Artist",
  "Sequential Artist",
  "3D Artist",
  "3D Modeler",
  "3D Generalist",
  "3D Sculptor",
  "Sculptor",
  "Painter",
  "Digital Painter",
  "Printmaker",
  "Ceramic Artist",
  "Installation Artist",
  "Mixed Media Artist",
  "Visual Artist",
  "Fine Artist",
  "Street Artist",
  "Tattoo Artist",
  "Calligrapher",
  "Lettering Artist",
  "Muralist",
  "Collage Artist",
  "Paper Artist",
  "Fiber Artist",
  "Textile Artist",
  "Glass Artist",
  "Woodworker",
  "Metal Artist",
  "Craft Artist",
  "Contemporary Artist",
  "Abstract Artist",
  "Portrait Artist",
  "Landscape Artist",
  "Sculptural Artist",
  "Generative Artist",
  "AI Artist",
  "NFT Artist",

  // Photography
  "Photographer",
  "Portrait Photographer",
  "Fashion Photographer",
  "Product Photographer",
  "Commercial Photographer",
  "Editorial Photographer",
  "Documentary Photographer",
  "Wedding Photographer",
  "Event Photographer",
  "Architectural Photographer",
  "Food Photographer",
  "Sports Photographer",
  "Street Photographer",
  "Landscape Photographer",
  "Travel Photographer",
  "Lifestyle Photographer",
  "Automotive Photographer",
  "Music Photographer",
  "Concert Photographer",
  "Film Photographer",
  "Fine Art Photographer",
  "Aerial Photographer",
  "Drone Photographer",
  "Wildlife Photographer",
  "Nature Photographer",
  "Real Estate Photographer",
  "Medical Photographer",
  "Scientific Photographer",
  "Photojournalist",
  "Photo Editor",
  "Digital Technician",
  "Retoucher",
  "Photo Retoucher",
  "Color Retoucher",

  // Film & Video
  "Filmmaker",
  "Director",
  "Film Director",
  "Creative Director",
  "Commercial Director",
  "Music Video Director",
  "Documentary Director",
  "Producer",
  "Film Producer",
  "Executive Producer",
  "Line Producer",
  "Associate Producer",
  "Cinematographer",
  "Director of Photography",
  "Videographer",
  "Video Editor",
  "Film Editor",
  "Assistant Editor",
  "Colorist",
  "Color Grader",
  "Screenwriter",
  "Scriptwriter",
  "Storyboard Artist",
  "Production Designer",
  "Set Designer",
  "Casting Director",
  "Assistant Director",
  "Production Assistant",
  "Gaffer",
  "Best Boy",
  "Grip",
  "Key Grip",
  "Camera Operator",
  "Camera Assistant",
  "Steadicam Operator",
  "Drone Operator",
  "Sound Designer",
  "Sound Editor",
  "Boom Operator",
  "Foley Artist",
  "Foley Editor",
  "Dialogue Editor",
  "Re-Recording Mixer",
  "VFX Artist",
  "Visual Effects Artist",
  "Compositor",
  "VFX Supervisor",
  "CG Artist",
  "CGI Artist",
  "Motion Picture Editor",
  "Location Manager",
  "Production Coordinator",
  "Script Supervisor",
  "Continuity Supervisor",

  // Animation & Motion
  "Animator",
  "2D Animator",
  "3D Animator",
  "Character Animator",
  "Motion Graphics Designer",
  "Motion Artist",
  "Stop Motion Animator",
  "Clay Animator",
  "Visual Effects Artist",
  "Rigger",
  "Storyboard Artist",
  "Previsualization Artist",
  "Previs Artist",
  "Layout Artist",
  "Background Artist",
  "Clean-Up Artist",
  "In-Between Artist",
  "Texture Artist",
  "Lighting Artist",
  "Environment Artist",
  "Character Designer",
  "Animation Director",
  "Animation Producer",
  "Motion Director",
  "Motion Art Director",
  "CG Generalist",
  "Technical Director",
  "FX Artist",

  // Writing & Editorial
  "Writer",
  "Copywriter",
  "Creative Writer",
  "Content Writer",
  "Technical Writer",
  "Screenwriter",
  "Scriptwriter",
  "Author",
  "Poet",
  "Journalist",
  "Editor",
  "Copy Editor",
  "Proofreader",
  "Blogger",
  "Essayist",
  "Columnist",
  "Lyricist",
  "Playwright",
  "Researcher",
  "Ghostwriter",
  "Speechwriter",
  "Brand Writer",
  "UX Writer",
  "Content Designer",
  "Content Strategist",
  "Editorial Writer",
  "News Writer",
  "Feature Writer",
  "Travel Writer",
  "Culture Writer",
  "Technical Editor",
  "Managing Editor",
  "Executive Editor",
  "Editorial Director",
  "Creative Editor",
  "Book Editor",
  "Developmental Editor",
  "Sub-Editor",
  "Fact Checker",
  "Translator",
  "Literary Translator",
  "Copy Chief",

  // Music & Audio
  "Musician",
  "Producer",
  "Music Producer",
  "Executive Music Producer",
  "Singer",
  "Songwriter",
  "Composer",
  "DJ",
  "Beatmaker",
  "Instrumentalist",
  "Vocalist",
  "Rapper",
  "MC",
  "Guitarist",
  "Bassist",
  "Drummer",
  "Pianist",
  "Keyboardist",
  "Violinist",
  "Cellist",
  "Saxophonist",
  "Trumpeter",
  "Percussionist",
  "Music Director",
  "Conductor",
  "Sound Artist",
  "Sound Designer",
  "Audio Engineer",
  "Mixing Engineer",
  "Mastering Engineer",
  "Recording Engineer",
  "Session Musician",
  "Live Sound Engineer",
  "Broadcast Engineer",
  "Audio Programmer",
  "Sound Engineer",
  "Music Supervisor",
  "A&R",
  "Music Curator",
  "Radio Producer",
  "Radio Host",
  "Podcast Producer",
  "Podcast Host",
  "Podcaster",
  "Voice Actor",
  "Voice Artist",
  "Voiceover Artist",
  "Narrator",
  "Foley Artist",
  "Sound Technician",

  // Fashion & Styling
  "Stylist",
  "Fashion Stylist",
  "Wardrobe Stylist",
  "Fashion Designer",
  "Costume Designer",
  "Fashion Photographer",
  "Fashion Editor",
  "Fashion Director",
  "Creative Director",
  "Art Director",
  "Model",
  "Fashion Model",
  "Runway Model",
  "Commercial Model",
  "Makeup Artist",
  "Hair Stylist",
  "Hair Designer",
  "Jewelry Designer",
  "Textile Designer",
  "Pattern Maker",
  "Tailor",
  "Seamstress",
  "Couturier",
  "Dressmaker",
  "Footwear Designer",
  "Accessory Designer",
  "Bag Designer",
  "Costume Stylist",
  "Fashion Buyer",
  "Fashion Consultant",
  "Fashion Illustrator",
  "Fashion Curator",
  "Fashion Writer",
  "Fashion Producer",
  "Fashion Merchandiser",
  "Fashion Entrepreneur",

  // Architecture & Spatial
  "Architect",
  "Landscape Architect",
  "Interior Designer",
  "Interior Architect",
  "Urban Designer",
  "Urban Planner",
  "Spatial Designer",
  "Exhibition Designer",
  "Set Designer",
  "Lighting Designer",
  "Furniture Designer",
  "Architectural Designer",
  "Architectural Technologist",
  "Building Designer",
  "Environmental Designer",
  "Sustainable Designer",
  "Conservation Architect",
  "Restoration Architect",
  "Historic Preservationist",
  "Parametric Designer",
  "BIM Specialist",
  "BIM Manager",
  "CAD Designer",
  "3D Visualizer",
  "Architectural Visualizer",
  "Architectural Illustrator",
  "Interior Stylist",
  "Space Planner",
  "Retail Designer",
  "Hospitality Designer",
  "Exhibition Designer",
  "Museum Designer",
  "Scenographer",

  // Marketing & Creative Direction
  "Art Director",
  "Creative Director",
  "Associate Creative Director",
  "Executive Creative Director",
  "Brand Strategist",
  "Creative Strategist",
  "Marketing Strategist",
  "Content Strategist",
  "Digital Strategist",
  "Social Media Manager",
  "Social Media Strategist",
  "Community Manager",
  "Publicist",
  "PR Specialist",
  "PR Manager",
  "Brand Manager",
  "Marketing Manager",
  "Digital Marketing Manager",
  "Growth Marketer",
  "Growth Manager",
  "Performance Marketer",
  "SEO Specialist",
  "SEO Strategist",
  "SEM Specialist",
  "Email Marketing Specialist",
  "Influencer Manager",
  "Talent Manager",
  "Partnerships Manager",
  "Community Strategist",
  "Creative Producer",
  "Creative Consultant",
  "Creative Researcher",
  "Brand Consultant",
  "Marketing Consultant",
  "Communications Specialist",
  "Communications Director",
  "Copy Director",
  "Creative Planner",
  "Account Director",
  "Account Manager",
  "Advertising Creative",
  "Advertising Strategist",

  // Business & Freelance
  "Founder",
  "Co-Founder",
  "Entrepreneur",
  "Freelancer",
  "Consultant",
  "Independent Creative",
  "Creative Entrepreneur",
  "Studio Founder",
  "Creative Consultant",
  "Business Owner",
  "Startup Founder",
  "CEO",
  "CTO",
  "COO",
  "Creative Business Owner",
  "Project Manager",
  "Product Manager",
  "Product Lead",
  "Product Owner",
  "Producer",
  "Creative Producer",
  "Operations Manager",
  "Operations Director",
  "Business Analyst",
  "Business Consultant",
  "Strategy Consultant",
  "Management Consultant",
  "Innovation Consultant",
  "Venture Builder",
  "Startup Advisor",
  "Mentor",
  "Coach",
  "Talent Manager",
  "Artist Manager",
  "Agent",
  "Booking Agent",

  // Research & Academia
  "Researcher",
  "Creative Researcher",
  "Design Researcher",
  "UX Researcher",
  "User Researcher",
  "Market Researcher",
  "Data Scientist",
  "Academic",
  "Educator",
  "Teacher",
  "Lecturer",
  "Professor",
  "Tutor",
  "Instructor",
  "Teaching Assistant",
  "Research Assistant",
  "Research Fellow",
  "Curator",
  "Art Curator",
  "Archivist",
  "Historian",
  "Art Historian",
  "Anthropologist",
  "Sociologist",
  "Psychologist",
  "Economist",
  "Scientist",
  "Biologist",
  "Physicist",
  "Chemist",
  "Environmental Scientist",
  "Cultural Researcher",
  "Design Historian",

  // Performance
  "Actor",
  "Actress",
  "Performer",
  "Dancer",
  "Choreographer",
  "Theatre Director",
  "Theatre Producer",
  "Stage Manager",
  "Comedian",
  "Magician",
  "Performance Artist",
  "Presenter",
  "Public Speaker",
  "Motivational Speaker",
  "Spoken Word Artist",
  "Poet",
  "Theatre Actor",
  "Stage Performer",
  "Circus Artist",
  "Acrobat",
  "Contortionist",
  "Drag Artist",
  "Burlesque Performer",
  "Puppeteer",
  "Storyteller",

  // Publishing & Media
  "Publisher",
  "Editor",
  "Art Editor",
  "Creative Editor",
  "Photo Editor",
  "Magazine Editor",
  "Editorial Director",
  "Content Creator",
  "Content Producer",
  "Blogger",
  "YouTuber",
  "Streamer",
  "Podcaster",
  "Influencer",
  "Creator",
  "Digital Creator",
  "Media Producer",
  "Media Director",
  "Broadcast Producer",
  "Broadcast Journalist",
  "News Producer",
  "News Editor",
  "TV Producer",
  "TV Director",
  "Radio Producer",
  "Radio Presenter",
  "Content Director",
  "Media Strategist",
  "Creator Manager",
  "Audience Development Manager",

  // Gaming
  "Game Designer",
  "Game Developer",
  "Game Programmer",
  "Game Producer",
  "Game Director",
  "Game Artist",
  "Game Writer",
  "Game Designer",
  "Level Designer",
  "Narrative Designer",
  "Character Designer",
  "Environment Artist",
  "Technical Artist",
  "Gameplay Programmer",
  "Graphics Programmer",
  "Engine Programmer",
  "UI Game Designer",
  "Game Animator",
  "Game Audio Designer",
  "Game Tester",
  "Game QA Tester",
  "Esports Player",
  "Esports Coach",
  "Esports Manager",
  "Streamer",
  "Gaming Creator",

  // Digital & Emerging
  "Digital Creator",
  "Content Creator",
  "Creative Technologist",
  "Digital Strategist",
  "Digital Artist",
  "Web3 Artist",
  "NFT Artist",
  "Generative Artist",
  "AI Artist",
  "AI Creative",
  "AI Designer",
  "AI Researcher",
  "AI Engineer",
  "Prompt Designer",
  "Prompt Engineer",
  "XR Designer",
  "AR Designer",
  "VR Designer",
  "Mixed Reality Designer",
  "Immersive Designer",
  "Experience Designer",
  "Metaverse Designer",
  "Blockchain Developer",
  "Blockchain Designer",
  "Web3 Developer",
  "Creative Coder",
  "Creative Programmer",
  "Digital Product Designer",
  "No-Code Developer",
  "Low-Code Developer",
  "Automation Specialist",
  "AR Artist",
  "VR Artist",
  "Interactive Artist",
  "Interactive Designer",
  "Generative Designer",
  "Digital Curator",

  // Education
  "Educator",
  "Teacher",
  "Lecturer",
  "Professor",
  "Tutor",
  "Instructor",
  "Course Creator",
  "Online Educator",
  "Teaching Artist",
  "Workshop Facilitator",
  "Workshop Leader",
  "Learning Designer",
  "Instructional Designer",
  "Curriculum Designer",
  "Education Consultant",
  "Academic Advisor",
  "Career Coach",
  "Career Advisor",
  "Student Mentor",

  // Wellness & Lifestyle
  "Life Coach",
  "Wellness Coach",
  "Fitness Coach",
  "Personal Trainer",
  "Yoga Instructor",
  "Pilates Instructor",
  "Nutritionist",
  "Chef",
  "Private Chef",
  "Food Stylist",
  "Food Writer",
  "Travel Creator",
  "Travel Writer",
  "Lifestyle Creator",
  "Lifestyle Blogger",

  // Food & Culinary
  "Chef",
  "Sous Chef",
  "Pastry Chef",
  "Baker",
  "Baker",
  "Chocolatier",
  "Barista",
  "Mixologist",
  "Food Photographer",
  "Food Stylist",
  "Food Critic",
  "Food Writer",
  "Recipe Developer",
  "Culinary Consultant",
  "Caterer",
  "Restaurateur",

  // Science & Engineering
  "Engineer",
  "Mechanical Engineer",
  "Electrical Engineer",
  "Civil Engineer",
  "Chemical Engineer",
  "Biomedical Engineer",
  "Aerospace Engineer",
  "Automotive Engineer",
  "Structural Engineer",
  "Environmental Engineer",
  "Industrial Engineer",
  "Mechatronics Engineer",
  "Robotics Engineer",
  "Software Engineer",
  "Computer Engineer",
  "Hardware Engineer",
  "Research Engineer",
  "R&D Engineer",
  "Product Engineer",
  "Design Engineer",
  "Materials Scientist",
  "Scientist",
  "Research Scientist",
  "Lab Technician",

  // Community & Social Impact
  "Community Organizer",
  "Community Manager",
  "Activist",
  "Advocate",
  "Nonprofit Founder",
  "Social Entrepreneur",
  "Social Worker",
  "Humanitarian",
  "Community Builder",
  "Youth Worker",
  "Program Manager",
  "Program Coordinator",
  "Fundraiser",
  "Philanthropist",
  "Volunteer Coordinator",

  // Other
  "Other",
] as const;

export type Role = (typeof roleNames)[number];

export const roles: Role[] = Array.from(new Set(roleNames));
